version: "3.9"
services:
  x-app: &default-app
    build:
      context: .
      target: app
    image: myugen/go-mss-twirp:latest
    tty: true
    networks:
      - default-net

  server:
    <<: *default-app
    container_name: app_server
    ports:
      - "8080:8080"
    command: [ 'server', 'up' ]

networks:
  default-net:
    driver: bridge