// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: github.com/myugen/go-mss-twirp/rpc/user/service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Mail     string `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserIn) Reset() {
	*x = UserIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIn) ProtoMessage() {}

func (x *UserIn) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIn.ProtoReflect.Descriptor instead.
func (*UserIn) Descriptor() ([]byte, []int) {
	return file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserIn) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserIn) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UserIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Mail     string `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserOut) Reset() {
	*x = UserOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOut) ProtoMessage() {}

func (x *UserOut) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOut.ProtoReflect.Descriptor instead.
func (*UserOut) Descriptor() ([]byte, []int) {
	return file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserOut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserOut) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserOut) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UserOut) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_github_com_myugen_go_mss_twirp_rpc_user_service_proto protoreflect.FileDescriptor

var file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDesc = []byte{
	0x0a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x79, 0x75,
	0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x73, 0x73, 0x2d, 0x74, 0x77, 0x69, 0x72, 0x70,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6d, 0x79, 0x75, 0x67, 0x65, 0x6e, 0x2e,
	0x67, 0x6f, 0x5f, 0x6d, 0x73, 0x73, 0x5f, 0x74, 0x77, 0x79, 0x72, 0x70, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x22, 0x4c, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x5d, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x55,
	0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x4d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x20, 0x2e, 0x6d, 0x79, 0x75, 0x67, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x5f, 0x6d, 0x73, 0x73,
	0x5f, 0x74, 0x77, 0x79, 0x72, 0x70, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x1a, 0x21, 0x2e, 0x6d, 0x79, 0x75, 0x67, 0x65, 0x6e, 0x2e, 0x67, 0x6f, 0x5f, 0x6d,
	0x73, 0x73, 0x5f, 0x74, 0x77, 0x79, 0x72, 0x70, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x75, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x79, 0x75, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x73,
	0x73, 0x2d, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDescOnce sync.Once
	file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDescData = file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDesc
)

func file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDescGZIP() []byte {
	file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDescOnce.Do(func() {
		file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDescData)
	})
	return file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDescData
}

var file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_goTypes = []interface{}{
	(*UserIn)(nil),  // 0: myugen.go_mss_twyrp.user.UserIn
	(*UserOut)(nil), // 1: myugen.go_mss_twyrp.user.UserOut
}
var file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_depIdxs = []int32{
	0, // 0: myugen.go_mss_twyrp.user.User.Create:input_type -> myugen.go_mss_twyrp.user.UserIn
	1, // 1: myugen.go_mss_twyrp.user.User.Create:output_type -> myugen.go_mss_twyrp.user.UserOut
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_init() }
func file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_init() {
	if File_github_com_myugen_go_mss_twirp_rpc_user_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_goTypes,
		DependencyIndexes: file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_depIdxs,
		MessageInfos:      file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_msgTypes,
	}.Build()
	File_github_com_myugen_go_mss_twirp_rpc_user_service_proto = out.File
	file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_rawDesc = nil
	file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_goTypes = nil
	file_github_com_myugen_go_mss_twirp_rpc_user_service_proto_depIdxs = nil
}
